#!/usr/bin/env bash
# display information about subdomains of a domain

print_info ()
{
  if [ -z "$2" ];
  then
     for var in www lb-01 web-01 web-02;
     do
      subdomain="$var.$1"
      destination=$(dig $subdomain | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
      record_type=$(dig $subdomain | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
      echo "This subdomain $var is a $record_type record and points to $destination"
     done
  elif [ -n "$2" ];
  then
    subdomain="$2.$1"
    destination=$(dig $subdomain | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
    record_type=$(dig $subdomain | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
    echo "This subdomain $2 is a $record_type record and points to $destination"
  fi
}

if [ -n "$1" ]
then
  print_info $1 $2
fi
