#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get -y install nginx 
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo service nginx status
sudo sed -i '/^[^#].*/location \/ {/a \                 return 200 "Hello World!\n";' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
