#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get -y install nginx 
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo service nginx status
find /var/www/html -name "*.html" -type f -exec rename 's/\.html$/.html.txt/' {} \;
echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
service nginx restart
