#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y install haproxy=2.7.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy

sudo bash -c 'cat >> /etc/haproxy/haproxy.cfg << EOF
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 54449-web-01 100.26.244.193:80 check
    server 54449-web-02 100.25.196.119:80 check
EOF'
